
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { FluidCursor } from "@/components/ui/cursorDemo"


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en" className="scroll-smooth cursor-none" suppressHydrationWarning>
      <body
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          <FluidCursor />

          {children}
        </ThemeProvider>

      </body>
    </html>
  );
}
